### ISSUE TITLE
Garbage collection of RxLoaderObserver when using RxLoaderManagerCompat 

### ISSUE THREAD

**Issue by sbuettner** [evant/rxloader#12]
The same problem describes in issue #10 seems to exist when using ```RxLoaderManagerCompat```. The ```RxLoaderObserver``` seems to get GC'ed.

**Comment by evant** [comment]
Sorry for the long delay, I figured out what the problem was. With fragments, it was getting into a state where it was attempted to add the loader before the fragment was attached to the activity, because the loader states are stored in a hidden fragment with retain instance state, it was failing to find that and just not storing the loader at all.

**Comment by sbuettner** [comment]
Thank you for looking into this.
